name: nbtest_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy<2
  - pandas
  - tensorflow=2.14.0
  - scikit-learn
  - jupyter
  - pip
  - pip:
      - --extra-index-url https://test.pypi.org/simple/
      - nbtest-plugin
      - nbtest-gen
      - nbtest-lab-extension
